// data/projects.js (or inside your component file)

export const projects = [
  {
    title: "Nexus - (Under development 🚧)",
    techStack: [
      "NodeJS",
      "Redis",
      "BullMQ",
      "Docker",
      "Cloudinary",
      "MySQL",
      "Express",
      "SSE",
    ],
    description: (
      <>
        Nexus is a <b> Node.js</b> based robust image compression pipeline
        designed with scalability and fault-tolerance in mind.
        <br></br>It simulates the ingestion-heavy systems used in modern content
        platforms; using <b>BullMQ</b> to handle the heavy job of image
        compression in the background and <b>MySQL</b> for job persistence.
      </>
    ),
    githubLink: "https://github.com/Pallavi2908/Nexus",
    liveLink: "https://github.com/Pallavi2908/Nexus",
    videoEmbedUrl: "",
  },
  {
    title: "BlogApp",
    techStack: [
      "NodeJS",
      "Redis",
      "Cloudinary",
      "EJS",
      "Express",
      "JWT",
      "MongoDB Atlas",
    ],
    description: (
      <>
        Full-stack blogging platform built with{" "}
        <b>Node.js, Express, and MongoDB</b>, featuring secure JWT
        authentication and bcrypt encryption. Integrated <b>Cloudinary</b> for
        scalable cloud image storage and Redis caching to reduce response times
        by 84%.<br></br>
        <br></br>
        Deployed on Render serving <b>20+</b> active users with RESTful API
        architecture.
      </>
    ),
    githubLink: "https://github.com/Pallavi2908/BlogApp",
    liveLink: "https://blogapp-lngd.onrender.com/users/create",
    videoEmbedUrl: "https://www.youtube.com/embed/Bada0W5NkbY",
  },
  {
    title: "Semantra",
    techStack: [
      "Python",

      "LangChain",
      "SPECTER2",
      "Mistral 7B",
      "Qdrant",
      "React.js",
      "TailwindCSS",
      "Figma",
    ],
    description: (
      <>
        <b>Semantra</b> is an <em>AI-powered medical insight tool</em> that
        leverages
        <b> FastAPI, LangChain, Mistral 7B and SPECTER2 embedding model</b> to
        decode complex medical documents and instantly answer user queries.
        <br></br>
        <br></br>
        With Qdrant vector search and real-time LLM reasoning, it transforms
        dense reports into simple summaries.
      </>
    ),
    githubLink: "https://github.com/Pallavi2908/Semantra",
    liveLink: "https://semantra-s9mw.onrender.com/static",
    videoEmbedUrl:
      "https://www.youtube.com/embed/y3ERG1dG8Vw?si=QXbnrQjrzB522gcf",
  },

  {
    title: "PsyFer",
    techStack: ["React.js", "TailwindCSS", "Figma", "Collaboration-based"],
    description: (
      <>
        A blend of Graphology and Large Language Models, letting users explore
        their personality traits via clean UI.
        <br></br>
        <b>Role : </b>
        <em>Web developer and UI/UX designer</em>
      </>
    ),
    githubLink: "https://github.com/Pallavi2908/Graphology-Website",
    liveLink: "https://psyfer.netlify.app/",
    videoEmbedUrl:
      "https://www.youtube.com/embed/FLpdbzGGmm4?si=O6HxlHs-x3u94soq",
  },
  {
    title: "WebWhiz",
    techStack: [
      "Claude-Haiku",
      "PlayWright",
      "all-MiniLM-L6-v2",
      "Python",
      "ChromaDB",
      "BeautifulSoup",
    ],
    description: (
      <>
        An <b>AI-powered web query agent</b> that classifies,
        <em>semantically matches, scrapes, summarizes, and caches</em> search
        results using <b>Anthropic's Claude 3.5 Haiku LLM</b>, embeddings
        generated by the
        <b> all-MiniLM-L6-v2 model</b>, and browser automation with Playwright
        and BeautifulSoup for extracting data.
        <br></br>
      </>
    ),
    githubLink: "https://github.com/Pallavi2908/WebWhiz",
    liveLink: "https://github.com/Pallavi2908/WebWhiz",
    videoEmbedUrl:
      "https://www.youtube.com/embed/HRpcYGBvlqs?si=epB041yLSj15U-Zi",
  },
  // Add more projects here...
];
